name: Build and Test

on:
  push:
    branches:
    - master
    - dev
    - v3
    - feature/*

jobs:
  build_and_test:
    name: Build and test
    strategy:
      matrix:
        os: [ 'windows-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK 2.1 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'

    - name: Setup .NET SDK 3.1 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    # - name: Setup .NET SDK 5
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: '5.x'

    # NOTE: the setup-msbuild task currently leverages ::add-path which is deprecated and so requires ACTIONS_ALLOW_UNSECURE_COMMANDS
    - name: Enable ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Disable ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=false" >> $GITHUB_ENV

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dir
        dotnet restore .

    - name: Build solution
      shell: pwsh
      run: |
        dir
        dotnet build . -c Debug -v minimal

    - name: Test solution
      shell: pwsh
      run: |
        dir
        dotnet test . -c Debug
